// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBm5FHJGCd4v1gZBcrk5CnmB2bx48un6Rk',
    appId: '1:464238250888:web:fae8b1eb21aec9ec72c83d',
    messagingSenderId: '464238250888',
    projectId: 'task-206ca',
    authDomain: 'task-206ca.firebaseapp.com',
    storageBucket: 'task-206ca.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMqreLvzo47rn9-3LERdxQugKVcsEttgA',
    appId: '1:464238250888:android:4d15f6ae28e576a872c83d',
    messagingSenderId: '464238250888',
    projectId: 'task-206ca',
    storageBucket: 'task-206ca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7cn1NW1lP_wqaIGIoEQdq11jt8Wlq4Os',
    appId: '1:464238250888:ios:a460af6cd532f0a072c83d',
    messagingSenderId: '464238250888',
    projectId: 'task-206ca',
    storageBucket: 'task-206ca.appspot.com',
    iosBundleId: 'com.example.task1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7cn1NW1lP_wqaIGIoEQdq11jt8Wlq4Os',
    appId: '1:464238250888:ios:a460af6cd532f0a072c83d',
    messagingSenderId: '464238250888',
    projectId: 'task-206ca',
    storageBucket: 'task-206ca.appspot.com',
    iosBundleId: 'com.example.task1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBm5FHJGCd4v1gZBcrk5CnmB2bx48un6Rk',
    appId: '1:464238250888:web:7730989c38ac6bd572c83d',
    messagingSenderId: '464238250888',
    projectId: 'task-206ca',
    authDomain: 'task-206ca.firebaseapp.com',
    storageBucket: 'task-206ca.appspot.com',
  );
}
